### ISSUE TITLE
Zookeeper version 3.4.10 is no longer available

### ISSUE THREAD

**Issue by vutny** [saltstack-formulas/zookeeper-formula#69]
The formula uses http://apache.osuosl.org/ Apache mirror to retrieve Zookeeper tarball by default, and it is no longer available there. So the tests are failing.

Since constantly updating the default version (and the file hash) is tedious, better to switch to the main Apache archive at https://archive.apache.org/dist/zookeeper/, where all recent versions are present.

**Comment by myii** [comment]
To give a hand (before and after):

* http://apache.osuosl.org/zookeeper/zookeeper-3.4.14/zookeeper-3.4.14.tar.gz
* https://archive.apache.org/dist/zookeeper/zookeeper-3.4.14/zookeeper-3.4.14.tar.gz

So [in the code](https://github.com/saltstack-formulas/zookeeper-formula/blob/219665ca8ec92c179ae406c8ac2aa0d7c1a92651/zookeeper/settings.sls#L18) (before and after):

* `http://apache.osuosl.org/zookeeper/' + version_name + '/' + version_name + '.tar.gz'`
* `http://archive.apache.org/dist/zookeeper/' ~ version_name ~ '/' ~ version_name ~ '.tar.gz'`

The checksums are available in the same directory as well so worth considering using those instead of having to [track manually in the formula](https://github.com/saltstack-formulas/zookeeper-formula/blob/219665ca8ec92c179ae406c8ac2aa0d7c1a92651/zookeeper/settings.sls#L20-L26).

**Comment by vutny** [comment]
Absolutely agreed. Just thought that it would be better to address dealing with checksums as a separate issue. The sooner we'd have working test suite, it will be easier to validate subsequent fixes.

**Comment by myii** [comment]
@vutny Have you got a plan for the test suite?  I'd encourage the use of the structure that's being used for `salt-formula`, which is in the process of being applied to the `nginx-formula` and `collectd-formula`.  The plan is to update `template-formula` with this as well.

**Comment by vutny** [comment]
This formula is rather old and has a lots of legacy. It would be too hard to "refactor" everything at once.
I'm not a big fan of `salt-kitchen` though, but I guess these `inspec` checks could done better here for sure. Anyway I'm totally vote for standard approaches and best practices.

**Comment by myii** [comment]
@vutny The linked PR will close this issue.
