### ISSUE TITLE
[FEATURE] Update to formula template

### ISSUE THREAD

**Issue by codeboyQ2n5ha45** [saltstack-formulas/zookeeper-formula#74]
Since this formula is quite outdated, I would like to pull in a change to replace this code and update it to the formula template. So that multiple OS and file switching can occur.

Here is the formula I currently have put together:   https://github.com/codeboyQ2n5ha45/zookeeper-formula

It basically uses the same code to that I used for the SaltStack Apache NiFi formula.

**Comment by myii** [comment]
@codeboyQ2n5ha45 We'll need to get some feedback from people who have contributed to this formula before and may still be using it in its current form.  By the way, have you done any analysis of how different your formula is to this existing one?  Would there be a significant number of breaking changes?

@vutny @cachedout Would you mind sharing your thoughts on this issue or any alternative suggestions?  For example, should we have a second `zookeeper-formula` instead of building on top of this one?

**Comment by wrender** [comment]
@myii  Yes. Basically it would be a breaking change to the old formula. But the old formula was outdated and broken anyways. So in that way it is not a breaking change, but a path forward.

**Comment by vutny** [comment]
I don't mind for new better approach. This formula indeed needs some improvements.
I doubt someone is interested in outdated partially working code.

**Comment by wrender** [comment]
Ok. Sounds good. I'll open a pull request.

**Comment by codeboyQ2n5ha45** [comment]
Pull request is open @vutny
